### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by NobrainerWeb** [ryanwachtl/silverstripe-foundation-forms#14]
Just added foundation forms module to a project, but i'm not quite sure how to use it.
Could you add some simple usage instructions to the readme?

**Comment by ryanwachtl** [comment]
Hi Thomas,

You can use 'FoundationForm' anywhere you would normally use 'Form'. It will automatically transform other forms like the login or forms built using the UserForms module.

I will work on some expanded docs, though.

You can also check out /code/FoundationFormPage.php for an example.

**Comment by NobrainerWeb** [comment]
Thank you, that's all i needed :-) did not look in that file.
If you just add the above on the readme, i think everyone will understand, even me ;-)
