### ISSUE TITLE
First Change for Userforms 4

### ISSUE THREAD

**Issue by tazzydemon** [ryanwachtl/silverstripe-foundation-forms#22]
I'm having a look at updating this for UserForms 4. I have also added some row and column extensions for doing big multi-column forms. These are already in use and thoroughly tested. 

FYI for Userforms 4 the updateForm() extension is no longer in the same place. It will require a change to UserForms since it has no argument and your extension will then be called by:

UserForm:
  extensions:
    - FoundationUserDefinedForm_Controller

and in UserForm.php line 46 add $this (which is a UserForm object as above)

		$this->extend('updateForm', $this);

**Comment by ryanwachtl** [comment]
Thank you, I've updated the extension to work with UserForm. This is now in master and will be released in version 1.1 soon.

**Comment by tazzydemon** [comment]
I'm now waiting with bated breath for F6! Thank you.
